// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package gocrunchybridge

import (
	"errors"
	"fmt"
)

const (
	// ClusterEnvironmentProduction is a ClusterEnvironment of type production.
	ClusterEnvironmentProduction ClusterEnvironment = "production"
	// ClusterEnvironmentDev is a ClusterEnvironment of type dev.
	ClusterEnvironmentDev ClusterEnvironment = "dev"
)

var ErrInvalidClusterEnvironment = errors.New("not a valid ClusterEnvironment")

// String implements the Stringer interface.
func (x ClusterEnvironment) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClusterEnvironment) IsValid() bool {
	_, err := ParseClusterEnvironment(string(x))
	return err == nil
}

var _ClusterEnvironmentValue = map[string]ClusterEnvironment{
	"production": ClusterEnvironmentProduction,
	"dev":        ClusterEnvironmentDev,
}

// ParseClusterEnvironment attempts to convert a string to a ClusterEnvironment.
func ParseClusterEnvironment(name string) (ClusterEnvironment, error) {
	if x, ok := _ClusterEnvironmentValue[name]; ok {
		return x, nil
	}
	return ClusterEnvironment(""), fmt.Errorf("%s is %w", name, ErrInvalidClusterEnvironment)
}

const (
	// ClusterProviderAws is a ClusterProvider of type aws.
	ClusterProviderAws ClusterProvider = "aws"
	// ClusterProviderGcp is a ClusterProvider of type gcp.
	ClusterProviderGcp ClusterProvider = "gcp"
	// ClusterProviderAzure is a ClusterProvider of type azure.
	ClusterProviderAzure ClusterProvider = "azure"
)

var ErrInvalidClusterProvider = errors.New("not a valid ClusterProvider")

// String implements the Stringer interface.
func (x ClusterProvider) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClusterProvider) IsValid() bool {
	_, err := ParseClusterProvider(string(x))
	return err == nil
}

var _ClusterProviderValue = map[string]ClusterProvider{
	"aws":   ClusterProviderAws,
	"gcp":   ClusterProviderGcp,
	"azure": ClusterProviderAzure,
}

// ParseClusterProvider attempts to convert a string to a ClusterProvider.
func ParseClusterProvider(name string) (ClusterProvider, error) {
	if x, ok := _ClusterProviderValue[name]; ok {
		return x, nil
	}
	return ClusterProvider(""), fmt.Errorf("%s is %w", name, ErrInvalidClusterProvider)
}
