name: Build, run all tests
on:
  pull_request:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22
        id: go

      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get and verify dependencies
        run: go mod download && go mod verify

      - name: Run all tests
        run: go test -tags integration -v ./...
        env:
          INTEGRATION_API_KEY: ${{ secrets.INTEGRATION_API_KEY }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
